// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://djgsjqtoiyiupbgrgdln.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRqZ3NqcXRvaXlpdXBiZ3JnZGxuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3NDE3NTUsImV4cCI6MjA2MDMxNzc1NX0._Hrwa4jJGdPj5n_e4TkgmfQOru2uXehxzbDwNC4PjmY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);